# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d7b45e5017304e9bfdc5d6b7548c51988ef4abab363f0a991f2da88dd9c2caa22cd92dc5a16ccbfbe63fde77f8c0a201470de5115b2c0471355e6f7d98ec1dc

test:
  secret_key_base: 933529dd816e74a51cda5b34ce77df47d2daf3054f707e3f8810a0feb24a4ba2749a865ab7a400ddd6b4194112e61695f5d5b7f43bda78b47be8dc06fbf7eb6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
